export function drawFooter(doc) {

  const pageHeight =
    doc.internal.pageSize.height;

  const startY =
    pageHeight - 70;



  // Green Line

  doc.setDrawColor(0,150,0);

  doc.setLineWidth(1);

  doc.line(
    10,
    startY,
    200,
    startY
  );



  // Products Heading

  doc.setTextColor(0,120,0);

  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(13);

  doc.text(
    "OUR PRODUCTS",
    15,
    startY + 10
  );



  doc.setTextColor(0,0,0);

  doc.setFont(
    "helvetica",
    "normal"
  );

  doc.setFontSize(11);



  doc.text(
    "• Haldi Powder",
    20,
    startY + 20
  );

  doc.text(
    "• Lal Mirchi Powder",
    20,
    startY + 28
  );

  doc.text(
    "• Dhana Powder",
    20,
    startY + 36
  );

  doc.text(
    "• Jeera Powder",
    90,
    startY + 20
  );

  doc.text(
    "• Garam Masala",
    90,
    startY + 28
  );

  doc.text(
    "• Kala Masala",
    90,
    startY + 36
  );



  // Thank You Box

  doc.setFillColor(230,255,230);

  doc.roundedRect(
    10,
    startY + 45,
    190,
    18,
    2,
    2,
    "F"
  );



  doc.setFont(
    "helvetica",
    "bold"
  );

  doc.setFontSize(11);

  doc.setTextColor(0,100,0);

  doc.text(
    "Thank you for choosing green, paperless billing.",
    105,
    startY + 56,
    {
      align: "center",
    }
  );



  doc.setTextColor(120);

  doc.setFontSize(8);

  doc.text(
    "Generated by Rajhans ERP",
    105,
    pageHeight - 5,
    {
      align: "center",
    }
  );

}